spring:
  application:
    name: bolmal

  config:
    activate:
      on-profile: local

  data:
    redis:
      host: localhost
      port: 6379
      password:

  main:
    allow-circular-references: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bolmal
    username: root
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  jwt:
    header: Authorization
    secret: ${JWT_SECRET}
    access-token-validity-in-seconds: 3600 # 액세스 토큰 유효 시간 (1시간)
    refresh-token-validity-in-seconds: 2592000 # 리프레시 토큰: 30일


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

springdoc:
  show-login-endpoint: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,env

  metrics:
    tags:
      application: bolmal

sentry:
  dsn:
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  traces-sample-rate: 1.0
  environment: local

cloud:
  aws:
    s3:
      bucket: bolmal-buckets
    credentials:
      accessKey: ${S3_ACCESSKEY}
      secretKey: ${S3_SECRETS}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

